### PR TITLE
add incremental local docs option to makefile

### PR DESCRIPTION
**Pull request by prasek**
run jekyll with  `--incremental` for faster editing using `make run_docs_local_incremental`

### CODE REVIEW

**Comment by prasek** [comment]
@jbw976 --incremental is experimental, and sometimes gets stuck: 
https://jekyllrb.com/docs/configuration/incremental-regeneration/

**Comment by jbw976** [comment]
@prasek can you add that note and the link as a comment, so folks using this later on will be aware of that?

**Comment by hasheddan** [comment]
@prasek want to add that note and then we can get this merged? :)

**Comment by prasek** [comment]
@jbw976 @hasheddan should be good to go, thx!

**Review by hasheddan — APPROVED** [review]

**Pull request merged**
