### PR TITLE
converted png images to next-gen formats

### PR DESCRIPTION
**Pull request by reveurguy**
Converted the remaining images to next-gen formats.
This means faster downloads and less data consumption and also minimized the network payloads which helps increase the performance of the site.

### CODE REVIEW

**Review by thephred — CHANGES_REQUESTED** [review]
This looks great! Thank you @reveurguy.

Could you rebase so as not to have merge from master commits in the PR?

**Comment by reveurguy** [comment]
thanks @thephred .
could the rebase be done while merging the PR? I have tried rebase earlier as well and that got quite messy.

**Review by thephred — APPROVED** [review]
Sure. Thank you 👍

**Comment by thephred** [comment]
@reveurguy I rebased and merged. Thank you again for your contribution!

**Pull request merged**
