### PR TITLE
Update scss files based on autoprefixer and add LF copyright footer

### LINKED ISSUE #54: Add required footer with Linux Foundation copyright text
One of the final steps for onboarding Crossplane into the CNCF (https://github.com/cncf/toc/issues/466) is to add the required footer to the crossplane.io website.

We did this recently on https://rook.io/ in https://github.com/rook/rook.github.io/pull/90/files. Use that PR as a reference for the content that should be added to crossplane.io in a footer, obviously using the crossplane.io styling though 😎

### PR DESCRIPTION
**Pull request by rathpc**
The options being used for the vscode autoprefixer plugin is:

```
  "autoprefixer.options": {
    "overrideBrowserslist": [
      "last 2 versions",
      "> 0.1%",
      "not dead",
      "IE 10"
    ]
  },
```

Resolves #54

Rendered Screenshot:
image

### CODE REVIEW

**Comment by rathpc** [comment]
> Ideally we'd have a way to preview these but a code level visual scan looks good.

Actually there is a way to preview in addition to the screenshot I added: https://rathpc.github.io/crossplane.github.io/

**Comment by thephred** [comment]
> > Ideally we'd have a way to preview these but a code level visual scan looks good.
> 
> Actually there is a way to preview in addition to the screenshot I added: https://rathpc.github.io/crossplane.github.io/

Indeed, I made an attempt at that but it failed somehow. I must have screwed up the URL somehow. 😒

**Comment by jbw976** [comment]
@rathpc thank you for taking this on quickly.  It seems to be missing the language for the crossplane authors copyright and documentation license, as mentioned in https://github.com/rook/rook.github.io/pull/90/files#r427388808. Example:

```
© Crossplane Authors 2020. Documentation distributed under CC-BY-4.0.
```

Is it possible to add that also, similar to https://rook.io/, https://kubernetes.io/, and https://prometheus.io/?

**Comment by hasheddan** [comment]
This would be helpful to be in a separate PR anyway given that Github was having issues building static sites this morning :sweat_smile:

**Comment by jbw976** [comment]
I was actually just going to ask if something is up with the build, I don't see @rathpc changes live on https://crossplane.io/ still and this was merged 1 hour ago :(

**Comment by hasheddan** [comment]
@jbw976 Yep github was having a rough time. Was going to push an empty commit to trigger rebuild but I'll just wait for this instead :+1:

**Comment by rathpc** [comment]
> @rathpc thank you for taking this on quickly. It seems to be missing the language for the crossplane authors copyright and documentation license, as mentioned in https://github.com/rook/rook.github.io/pull/90/files#r427388808. Example:
> 
> ```
> © Crossplane Authors 2020. Documentation distributed under CC-BY-4.0.
> ```
> 
> (note that CC-BY-4.0 links to https://creativecommons.org/licenses/by/4.0)
> 
> Is it possible to add that also, similar to https://rook.io/, https://kubernetes.io/, and https://prometheus.io/?

I can add that now

**Pull request merged**
